[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
serverAddress = "localhost"
serverPort = 8501

[theme]
base = "dark"
primaryColor = "#0066ff"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "sans serif"

[deploy]
aptSources = [
    "deb http://deb.debian.org/debian bullseye main",
    "deb http://deb.debian.org/debian-security bullseye-security main",
    "deb http://deb.debian.org/debian bullseye-updates main"
]
